### PR TITLE
Actually fix github

### PR DESCRIPTION
**Pull request by AstraLuma**
https://github.com/voxpupuli/puppet-caddy/pull/76 was incomplete

### CODE REVIEW

**Comment by smortex** [comment]
Hey @AstraLuma!

We just merged some long-waiting PR that fixed a bunch of issues on the module and we now have CI \o/

Do you mind rebasing you changes on top of the master branch:

From your working directory:

```
git fetch origin         # Download the latest code we have here
git rebase origin/master # "Move" your commits on top of the main branch
git push -f              # Send the changes (-f is required because we re-wrote history)
```

Thank you!

**Review by smortex — APPROVED** [review]
Looks good, thanks!

**Comment by smortex** [comment]
Fun fact, the module does not detect the source change and the config does not work as expected. Good news is that it is not related to your changes: the module needs some work.

I started to fix this, and will open a PR on top of this one soon™ :unamused:.

**Comment by AstraLuma** [comment]
If my work is fine and not reducing functionality in any way, can you please merge my one-character fix?

**Comment by smortex** [comment]
> If my work is fine and not reducing functionality in any way, can you please merge my one-character fix?

Let's do this: my WIP is already out of control :stuck_out_tongue_winking_eye:

**Comment by smortex** [comment]
@AstraLuma I opened a bunch of issues and PR to fix what I saw.  Feel free to comment / review: I am not (yet) a user of Caddy and my experience is limited, you may have some relevant insights!

**Comment by AstraLuma** [comment]
> @AstraLuma I opened a bunch of issues and PR to fix what I saw. Feel free to comment / review: I am not (yet) a user of Caddy and my experience is limited, you may have some relevant insights!

Feel free to at me on anything specific.

**Pull request merged**
